/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_PDFPage */

#ifndef _Included_org_libharu_PDFPage
#define _Included_org_libharu_PDFPage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libharu_PDFPage
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_libharu_PDFPage
 * Method:    create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libharu_PDFPage
 * Method:    insertPage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_insertPage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setHeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setHeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_PDFPage
 * Method:    getWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_PDFPage_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PDFPage
 * Method:    getHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_PDFPage_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PDFPage
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_PDFPage_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setLineCap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setLineCap
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setLineJoin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setLineJoin
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setRGBFill
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setRGBFill
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_PDFPage
 * Method:    setRGBStroke
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_setRGBStroke
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_PDFPage
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_libharu_PDFPage
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_lineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_libharu_PDFPage
 * Method:    stroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFPage_stroke
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
