/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_PDFDocument */

#ifndef _Included_org_libharu_PDFDocument
#define _Included_org_libharu_PDFDocument
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libharu_PDFDocument
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFDocument_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_libharu_PDFDocument
 * Method:    create
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_libharu_PDFDocument_create__
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PDFDocument
 * Method:    create
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libharu_PDFDocument_create__I
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_libharu_PDFDocument
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFDocument_free
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PDFDocument
 * Method:    freeDoc
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFDocument_freeDoc
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_libharu_PDFDocument
 * Method:    freeDocAll
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PDFDocument_freeDocAll
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_libharu_PDFDocument
 * Method:    saveToFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libharu_PDFDocument_saveToFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_libharu_PDFDocument
 * Method:    hasDoc
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_libharu_PDFDocument_hasDoc
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
