/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libharu_PdfPage */

#ifndef _Included_org_libharu_PdfPage
#define _Included_org_libharu_PdfPage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_libharu_PdfPage
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_initIDs
  (JNIEnv *, jclass);

/*
 * Class:     org_libharu_PdfPage
 * Method:    create
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_create
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libharu_PdfPage
 * Method:    insertPage
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_insertPage
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setSize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setSize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setHeight
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setHeight
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_PdfPage
 * Method:    getWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_PdfPage_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PdfPage
 * Method:    getHeight
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_PdfPage_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PdfPage
 * Method:    getLineWidth
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_org_libharu_PdfPage_getLineWidth
  (JNIEnv *, jobject);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setLineCap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setLineCap
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setLineJoin
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setLineJoin
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setLineWidth
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setLineWidth
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setRGBFill
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setRGBFill
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_PdfPage
 * Method:    setRGBStroke
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_setRGBStroke
  (JNIEnv *, jobject, jfloat, jfloat, jfloat);

/*
 * Class:     org_libharu_PdfPage
 * Method:    moveTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_moveTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_libharu_PdfPage
 * Method:    lineTo
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_lineTo
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     org_libharu_PdfPage
 * Method:    stroke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libharu_PdfPage_stroke
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
